### ISSUE TITLE
About unsupervised training

### ISSUE THREAD

**Issue by congcongdan** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#23] opened 2019-09-17 07:22 UTC
Hi, thanks for the nice work! I just wonder how could I fine tune it through my own training set without groundtruth since it is an unsupervised learning in the paper.thanks

**Comment by AlessioTonioni** [comment] 2019-09-17 20:49
You can start from Stereo_Online_Adaptation.py and modify it to save the weight of the network once trained. 
The line for the unsupervised loss computation is this one:
https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/blob/33c3b924e0694f9bf7668381a2a21cfb6a4a4b0b/Stereo_Online_Adaptation.py#L70

**Comment by congcongdan** [comment] 2019-09-19 03:03
Thanks for your reply! Could you tell me a little more specificly about how to modify the code?

**Comment by AlessioTonioni** [comment] 2019-09-20 15:28
probably the easiest thing will be to start from Train.py and modify this line:
https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/blob/33c3b924e0694f9bf7668381a2a21cfb6a4a4b0b/Train.py#L99
with this line:
https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/blob/33c3b924e0694f9bf7668381a2a21cfb6a4a4b0b/Stereo_Online_Adaptation.py#L70
There might be other small things to fix

**Comment by congcongdan** [comment] 2019-09-24 08:05
**Hi, thanks for your answer! However, when I am trying to training to train it, I find the following problem no matter I am using supervised or unsupervised method.**

Traceback (most recent call last):
  File "Train.py", line 187, in <module>
    main(args)
  File "Train.py", line 98, in main
    assert(len(args.lossWeights)==len(predictions))
TypeError: object of type 'NoneType' has no len()

**I use the following command:**
python3 Train.py --trainingSet ./list.csv -o ./OUTPUT --imageShape 960 3130

**when I try to annotate the line:
    "assert(len(args.lossWeights)==len(predictions))"
and the following mistake appears:**
Traceback (most recent call last):
  File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= -1
     [[{{node random_uniform_1}} = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0](random_uniform_1/shape, random_uniform_1/min, sub_3)]]
     [[{{node input_reader/training_set_reader/IteratorGetNext}} = IteratorGetNext[output_shapes=[[4,960,3130,3], [4,960,3130,3], [4,960,3130,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_reader/training_set_reader/OneShotIterator)]]
     [[{{node input_reader/training_set_reader/IteratorGetNext/_23}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_108_input_reader/training_set_reader/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "Train.py", line 186, in <module>
    main(args)
  File "Train.py", line 138, in main
    fetches = sess.run(tf_fetches,options=run_options)
  File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= -1
     [[{{node random_uniform_1}} = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0](random_uniform_1/shape, random_uniform_1/min, sub_3)]]
     [[{{node input_reader/training_set_reader/IteratorGetNext}} = IteratorGetNext[output_shapes=[[4,960,3130,3], [4,960,3130,3], [4,960,3130,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_reader/training_set_reader/OneShotIterator)]]
     [[{{node input_reader/training_set_reader/IteratorGetNext/_23}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_108_input_reader/training_set_reader/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by redcping** [comment] 2019-10-18 07:34
> **Hi, thanks for your answer! However, when I am trying to train it, I find the following problem no matter using supervised or unsupervised method.**
> 
> Traceback (most recent call last):
> File "Train.py", line 187, in
> main(args)
> File "Train.py", line 98, in main
> assert(len(args.lossWeights)==len(predictions))
> TypeError: object of type 'NoneType' has no len()
> 
> **I use the following command:**
> python3 Train.py --trainingSet ./list.csv -o ./OUTPUT --imageShape 960 3130
> 
> **when I try to annotate the line: "assert(len(args.lossWeights)==len(predictions))" and the following mistake appears:**
> Traceback (most recent call last):
> File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
> return fn(*args)
> File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
> options, feed_dict, fetch_list, target_list, run_metadata)
> File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
> run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= -1
> [[{{node random_uniform_1}} = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0](random_uniform_1/shape, random_uniform_1/min, sub_3)]]
> [[{{node input_reader/training_set_reader/IteratorGetNext}} = IteratorGetNext[output_shapes=[[4,960,3130,3], [4,960,3130,3], [4,960,3130,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_reader/training_set_reader/OneShotIterator)]]
> [[{{node input_reader/training_set_reader/IteratorGetNext/_23}} = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_108_input_reader/training_set_reader/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "Train.py", line 186, in
> main(args)
> File "Train.py", line 138, in main
> fetches = sess.run(tf_fetches,options=run_options)
> File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
> run_metadata_ptr)
> File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
> feed_dict_tensor, options, run_metadata)
> File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
> run_metadata)
> File "/home/ram-lab/anaconda3/envs/tensorflow11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= -1
> [[{{node random_uniform_1}} = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0](random_uniform_1/shape, random_uniform_1/min, sub_3)]]
> [[{{node input_reader/training_set_reader/IteratorGetNext}} = IteratorGetNext[output_shapes=[[4,960,3130,3], [4,960,3130,3], [4,960,3130,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_reader/training_set_reader/OneShotIterator)]]
> [[{{node input_reader/training_set_reader/IteratorGetNext/_23}} = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_108_input_reader/training_set_reader/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]

I have the same problem, and the problem is made by the function  of preprocessing.random_crop() in data_reader.py when is_training is true.  You'd better use resize_image_with_crop_or_pad().

**Comment by redcping** [comment] 2019-10-18 07:34
I have the same problem, and the problem is made by the function  of preprocessing.random_crop() in data_reader.py when is_training is true.  You'd better use resize_image_with_crop_or_pad().

**Comment by redcping** [comment] 2019-10-18 07:35
@congcongdan I have the same problem, and the problem is made by the function  of preprocessing.random_crop() in data_reader.py when is_training is true.  You'd better use resize_image_with_crop_or_pad().

**Comment by AlessioTonioni** [comment] 2019-10-18 09:24
@redcping  Thank you for debugging this out, if the source of the error is the `preprocessing.random_crop()` function it probably means that you are trying to get a crop bigger than the input image. You do not get the error with `resize_image_with_crop_or_pad()` because the function automatically pads the image if the input resolution is lower than the expected one. I will add a check in the code of `random_crop()` to explicitly check for this and produce a more meaningful error message.

**Comment by AlessioTonioni** [comment] 2019-11-12 21:32
Fixed in 20add4c

**Closed by AlessioTonioni** 2019-11-12 21:32 UTC
